# Generated by Django 2.1.15 on 2020-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
